#!/usr/bin/env python
# encoding: utf-8

import tweepy
import json
import twitter_credentials
import wget

def get_all_tweets(screen_name):
#Twitter API credentials
    auth = tweepy.OAuthHandler(twitter_credentials.CONSUMER_KEY, twitter_credentials.CONSUMER_SECRET)
    auth.set_access_token(twitter_credentials.ACCESS_TOKEN, twitter_credentials.ACCESS_TOKEN_SECRET)
    api = tweepy.API(auth)

    #use a list to save all the tweets
    alltweets = []
    api.search(q="puppy filter:images")
    new_tweets = api.user_timeline(screen_name = screen_name,count=20,include_rts =False,exclude_replies=True)

    #save most recent tweets because user_timeline only allow us to get 20 tweets at a time
    alltweets.extend(new_tweets)

    #save the id of the last tweet for iteration
    last_id = alltweets[-1].id-1
    #keep grabbing tweets until there are no tweets left to grab, ignoring retweets and replies
    while len(new_tweets) > 0:
        for tweet in api.user_timeline(screen_name = screen_name,max_id = last_id):
            new_tweets.append(tweet)
        alltweets.extend(new_tweets)

        #get the last_id so we can get earlier tweets
        last_id = alltweets[-1].id - 1
        if(len(alltweets) > 15):
            break
        print ("...{} tweets downloaded so far".format(len(alltweets)))
        #assume that either each tweet has only one media attachment or we only care about the first one
    media_files = set()
    for photo in alltweets :
        media = photo.entities.get('media',[])
        if len(media) > 0 :
            media_files.add(media[0]['media_url'])
    for media_file in media_files:
        wget.download(media_file)


    #write tweet objects to JSON
    file = open('tweet.json', 'w')
    print ("Writing tweet objects to JSON please wait...")
    for status in alltweets:
        json.dump(status._json,file,sort_keys = True,indent = 4)
    print ("Done")
    file.close()

if __name__ == '__main__':
    #pass in the username of the account you want to download
    get_all_tweets_with_images("@BU_Tweets")
